spring:
  profiles:
    active: ${APP_ENV:dev}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APP_URL:http://localhost:8080}

security:
  credentials:
    admin-username: ${ADMIN_USERNAME:admin}
    admin-password: ${ADMIN_PASSWORD:password}
  keys:
    public: classpath:app.pub
    private: classpath:app.key
