spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APP_URL:http://localhost:8080}
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-plaform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true

security:
  credentials:
    admin-username: ${ADMIN_USERNAME:admin}
    admin-password: ${ADMIN_PASSWORD:password}
  keys:
    public: classpath:app.pub
    private: classpath:app.key
